export enum TenantLifecycleEventType {
  TENANT_CREATED = 'TENANT_CREATED',
  TENANT_UPDATED = 'TENANT_UPDATED',
  TENANT_STATUS_UPDATED = 'TENANT_STATUS_UPDATED',
  TENANT_APPS_UPDATED = 'TENANT_APPS_UPDATED',
  TENANT_PROVISIONED = 'TENANT_PROVISIONED',
  TENANT_DECOMMISSIONED = 'TENANT_DECOMMISSIONED',
  TENANT_DELETED = 'TENANT_DELETED',
}

